### ISSUE TITLE
Hanging process left over after quit

### ISSUE THREAD

**Issue by nfenclova** [RetroShare/RetroShare#1258]
Hi

I am running RetroShare compiled from git and everytime i quit the application, I am left with a process busy spinning at 100% CPU load. I was able to acquire the following stacktrace using gdb:

```
#0  0x00007f49b79a10b6 in pthread_rwlock_wrlock () at /usr/lib/libpthread.so.0
#1  0x00007f49bad4dbda in CRYPTO_THREAD_write_lock () at /usr/lib/libcrypto.so.1.1
#2  0x00007f49bad1c9d5 in RAND_get_rand_method () at /usr/lib/libcrypto.so.1.1
#3  0x00007f49bad1cc21 in RAND_bytes () at /usr/lib/libcrypto.so.1.1
#4  0x00007f49bacec33c in EVP_CIPHER_CTX_rand_key () at /usr/lib/libcrypto.so.1.1
#5  0x00007f49bacf0ab3 in EVP_SealInit () at /usr/lib/libcrypto.so.1.1
#6  0x000055ad0d9e6dc6 in AuthSSLimpl::encrypt(void*&, int&, void const*, int, t_RsGenericIdType<16u, false, 1u> const&) ()
#7  0x000055ad0d9fdfb3 in BinEncryptedFileInterface::senddata(void*, int) ()
#8  0x000055ad0da06926 in pqiSSLstore::encryptedSendItems(std::__cxx11::list<RsItem*, std::allocator<RsItem*> > const&) ()
#9  0x000055ad0d9f8ef1 in p3Config::saveConfig() ()
#10 0x000055ad0dbd2648 in p3GxsTrans::~p3GxsTrans() ()
#11 0x000055ad0dbd2889 in p3GxsTrans::~p3GxsTrans() ()
#12 0x000055ad0dc6b5a9 in RsServer::~RsServer() ()
#13 0x00007f49b6cdbf2c in __run_exit_handlers () at /usr/lib/libc.so.6
#14 0x00007f49b6cdc05a in  () at /usr/lib/libc.so.6
#15 0x00007f49b6cc6072 in __libc_start_main () at /usr/lib/libc.so.6
#16 0x000055ad0d51a59a in _start ()
```
This is a trace from the parent process spinning at 100% load with all of its 16 thread being at 0% load. To me, it looks like someone is not releasing the lock the main thread is trying to acquire. I upgraded to the git version since I had the same behaviour using the 0.6.4 release and I was hoping it was fixed already.

**Comment by G10h4ck** [comment]
AFAIR this bug have been fixed, reopen it if it still happens with current RetroShare
