### ISSUE TITLE
Yet another deadlock -- Gdb backtrace

### ISSUE THREAD

**Issue by dtschmitz** [RetroShare/RetroShare#1380]
This with today's commit:
`Thread 132 (Thread 0x7fffae7fc700 (LWP 1586)):
#0  0x00007ffff589f0e7 in write () at /usr/lib/libpthread.so.0
#1  0x00007ffff7806167 in  () at /usr/lib/libcrypto.so.1.1
#2  0x00007ffff780130a in  () at /usr/lib/libcrypto.so.1.1
#3  0x00007ffff7800343 in  () at /usr/lib/libcrypto.so.1.1
#4  0x00007ffff7800803 in BIO_write () at /usr/lib/libcrypto.so.1.1
#5  0x00007ffff7a4a768 in  () at /usr/lib/libssl.so.1.1
#6  0x00007ffff7a4b6ca in  () at /usr/lib/libssl.so.1.1
#7  0x00007ffff7a552fa in  () at /usr/lib/libssl.so.1.1
#8  0x00007ffff7a53396 in  () at /usr/lib/libssl.so.1.1
#9  0x00007ffff7a5e620 in SSL_shutdown () at /usr/lib/libssl.so.1.1
#10 0x0000555556c00be0 in pqissl::reset_locked() (this=0x7fffa0777620) at pqi/pqissl.cc:205
#11 0x0000555556c054bd in pqissl::readdata(void*, int) (this=0x7fffa0777620, data=0x7fff90000b40, len=8)
    at pqi/pqissl.cc:1667
#12 0x0000555556b7cab6 in pqistreamer::handleincoming_locked() (this=0x7fffa0777780)
    at pqi/pqistreamer.cc:740
--Type <RET> for more, q to quit, c to continue without paging--c
#13 0x0000555556b7bbbb in pqistreamer::tick_recv(unsigned int) (this=0x7fffa0777780, timeout=10000) at pqi/pqistreamer.cc:294
#14 0x0000555556b812d1 in pqithreadstreamer::data_tick() (this=0x7fffa0777780) at pqi/pqithreadstreamer.cc:74
#15 0x000055555692d1d5 in RsTickingThread::runloop() (this=0x7fffa0777950) at util/rsthreads.cc:250
#16 0x000055555692cb71 in RsThread::go() (this=0x7fffa0777950) at util/rsthreads.cc:67
#17 0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x7fffa0777950) at util/rsthreads.cc:87
#18 0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#19 0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 116 (Thread 0x7fff7f7fe700 (LWP 32243)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c05c07 in pqissl::moretoread(unsigned int) (this=0x7fffa07850f0, usec=10000) at pqi/pqissl.cc:1771
#2  0x0000555556b7bb9e in pqistreamer::tick_recv(unsigned int) (this=0x7fffa0785250, timeout=10000) at pqi/pqistreamer.cc:292
#3  0x0000555556b812d1 in pqithreadstreamer::data_tick() (this=0x7fffa0785250) at pqi/pqithreadstreamer.cc:74
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x7fffa0785420) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x7fffa0785420) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x7fffa0785420) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 40 (Thread 0x7fffacff9700 (LWP 22644)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c05c07 in pqissl::moretoread(unsigned int) (this=0x7fffa0784180, usec=10000) at pqi/pqissl.cc:1771
#2  0x0000555556b7bb9e in pqistreamer::tick_recv(unsigned int) (this=0x7fffa07842e0, timeout=10000) at pqi/pqistreamer.cc:292
#3  0x0000555556b812d1 in pqithreadstreamer::data_tick() (this=0x7fffa07842e0) at pqi/pqithreadstreamer.cc:74
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x7fffa07844b0) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x7fffa07844b0) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x7fffa07844b0) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 39 (Thread 0x7fffad7fa700 (LWP 22643)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c05c07 in pqissl::moretoread(unsigned int) (this=0x7fffa0789e20, usec=10000) at pqi/pqissl.cc:1771
#2  0x0000555556b7bb9e in pqistreamer::tick_recv(unsigned int) (this=0x7fffa0789f80, timeout=10000) at pqi/pqistreamer.cc:292
#3  0x0000555556b812d1 in pqithreadstreamer::data_tick() (this=0x7fffa0789f80) at pqi/pqithreadstreamer.cc:74
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x7fffa078a150) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x7fffa078a150) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x7fffa078a150) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 38 (Thread 0x7fffaeffd700 (LWP 22642)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c05c07 in pqissl::moretoread(unsigned int) (this=0x7fffa0782340, usec=10000) at pqi/pqissl.cc:1771
#2  0x0000555556b7bb9e in pqistreamer::tick_recv(unsigned int) (this=0x7fffa07824a0, timeout=10000) at pqi/pqistreamer.cc:292
#3  0x0000555556b812d1 in pqithreadstreamer::data_tick() (this=0x7fffa07824a0) at pqi/pqithreadstreamer.cc:74
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x7fffa0782670) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x7fffa0782670) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x7fffa0782670) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 37 (Thread 0x7fffadffb700 (LWP 22639)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c05c07 in pqissl::moretoread(unsigned int) (this=0x7fffa077ca40, usec=10000) at pqi/pqissl.cc:1771
#2  0x0000555556b7bb9e in pqistreamer::tick_recv(unsigned int) (this=0x7fffa077cba0, timeout=10000) at pqi/pqistreamer.cc:292
#3  0x0000555556b812d1 in pqithreadstreamer::data_tick() (this=0x7fffa077cba0) at pqi/pqithreadstreamer.cc:74
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x7fffa077cd70) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x7fffa077cd70) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x7fffa077cd70) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 33 (Thread 0x7fffaf7fe700 (LWP 22634)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=200000) at util/rstime.cc:42
#3  0x0000555556829df6 in RsServer::data_tick() (this=0x555557b719e0 <RsControl::instance()::rsicontrol>) at rsserver/p3face-server.cc:142
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555557b719e8 <RsControl::instance()::rsicontrol+8>) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555557b719e8 <RsControl::instance()::rsicontrol+8>) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555557b719e8 <RsControl::instance()::rsicontrol+8>) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 32 (Thread 0x7fffaffff700 (LWP 22633)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff54625ae in sleep () at /usr/lib/libc.so.6
#2  0x0000555556c47d18 in UdpBitDht::run() (this=0x5555582e4d60) at udp/udpbitdht.cc:335
#3  0x0000555556c75b43 in bdthread_init(void*) (p=0x5555582e4d70) at util/bdthreads.cc:52
#4  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 31 (Thread 0x7fffb8ff9700 (LWP 22632)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df8c in rstime::rs_usleep(unsigned int) (micro_seconds=1000000) at util/rstime.cc:38
#3  0x000055555692d441 in RsQueueThread::data_tick() (this=0x55555839b408) at util/rsthreads.cc:293
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x55555839b408) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x55555839b408) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x55555839b408) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 30 (Thread 0x7fffb97fa700 (LWP 22631)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df82 in rstime::rs_usleep(unsigned int) (micro_seconds=1000000) at util/rstime.cc:37
#3  0x0000555556bc7fe2 in ftController::data_tick() (this=0x555558163000) at ft/ftcontroller.cc:217
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555558163000) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555558163000) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555558163000) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 29 (Thread 0x7fffb9ffb700 (LWP 22630)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df8c in rstime::rs_usleep(unsigned int) (micro_seconds=1000000) at util/rstime.cc:38
#3  0x0000555556ad640b in LocalDirectoryUpdater::data_tick() (this=0x5555583622e0) at file_sharing/directory_updater.cc:106
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555583622e8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555583622e8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555583622e8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 28 (Thread 0x7fffba7fc700 (LWP 22629)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff54625ae in sleep () at /usr/lib/libc.so.6
#2  0x0000555556aec56f in ftExtraList::data_tick() (this=0x5555582cd4a0) at ft/ftextralist.cc:81
#3  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555582cd4a0) at util/rsthreads.cc:250
#4  0x000055555692cb71 in RsThread::go() (this=0x5555582cd4a0) at util/rsthreads.cc:67
#5  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555582cd4a0) at util/rsthreads.cc:87
#6  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 27 (Thread 0x7fffbaffd700 (LWP 22628)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=500000) at util/rstime.cc:42
#3  0x0000555556993590 in RsGxsNetService::data_tick() (this=0x5555582f64d0) at gxs/rsgxsnetservice.cc:1989
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555582f6538) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555582f6538) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555582f6538) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 26 (Thread 0x7fffbb7fe700 (LWP 22627)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556958e42 in RsGenExchange::data_tick() (this=0x5555582f5e00) at gxs/rsgenexchange.cc:137
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555582f5e08) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555582f5e08) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555582f5e08) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 25 (Thread 0x7fffbbfff700 (LWP 22626)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=500000) at util/rstime.cc:42
#3  0x0000555556993590 in RsGxsNetService::data_tick() (this=0x5555585ab390) at gxs/rsgxsnetservice.cc:1989
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555585ab3f8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555585ab3f8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555585ab3f8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 24 (Thread 0x7fffc4ff9700 (LWP 22625)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=500000) at util/rstime.cc:42
#3  0x0000555556993590 in RsGxsNetService::data_tick() (this=0x5555583870a0) at gxs/rsgxsnetservice.cc:1989
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555558387108) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555558387108) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555558387108) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 23 (Thread 0x7fffc57fa700 (LWP 22624)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=500000) at util/rstime.cc:42
#3  0x0000555556993590 in RsGxsNetService::data_tick() (this=0x555558311f50) at gxs/rsgxsnetservice.cc:1989
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555558311fb8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555558311fb8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555558311fb8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 22 (Thread 0x7fffc5ffb700 (LWP 22623)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=500000) at util/rstime.cc:42
#3  0x0000555556993590 in RsGxsNetService::data_tick() (this=0x5555582d7a70) at gxs/rsgxsnetservice.cc:1989
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555582d7ad8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555582d7ad8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555582d7ad8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 21 (Thread 0x7fffc67fc700 (LWP 22622)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=500000) at util/rstime.cc:42
#3  0x0000555556993590 in RsGxsNetService::data_tick() (this=0x5555582d7390) at gxs/rsgxsnetservice.cc:1989
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555582d73f8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555582d73f8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555582d73f8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 20 (Thread 0x7fffc6ffd700 (LWP 22621)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556958e42 in RsGenExchange::data_tick() (this=0x5555585aacd0) at gxs/rsgenexchange.cc:137
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555585aacd8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555585aacd8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555585aacd8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 19 (Thread 0x7fffc77fe700 (LWP 22620)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556958e42 in RsGenExchange::data_tick() (this=0x555558386af0) at gxs/rsgenexchange.cc:137
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555558386af8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555558386af8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555558386af8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 18 (Thread 0x7fffc7fff700 (LWP 22619)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556958e42 in RsGenExchange::data_tick() (this=0x5555583119e0) at gxs/rsgenexchange.cc:137
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555583119e8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555583119e8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555583119e8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 17 (Thread 0x7fffdcb22700 (LWP 22618)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556958e42 in RsGenExchange::data_tick() (this=0x5555582d6d10) at gxs/rsgenexchange.cc:137
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555582d6d18) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555582d6d18) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555582d6d18) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7fffdd323700 (LWP 22617)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556958e42 in RsGenExchange::data_tick() (this=0x5555585cd940) at gxs/rsgenexchange.cc:137
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x5555585cd948) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x5555585cd948) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x5555585cd948) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7fffddb24700 (LWP 22616)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df82 in rstime::rs_usleep(unsigned int) (micro_seconds=1000000) at util/rstime.cc:37
#3  0x00005555569cc3c3 in RsGxsNetTunnelService::data_tick() (this=0x555557c09690) at gxs/rsgxsnettunnel.cc:759
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555557c09698) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555557c09698) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555557c09698) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7fffde325700 (LWP 22615)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df82 in rstime::rs_usleep(unsigned int) (micro_seconds=1000000) at util/rstime.cc:37
#3  0x00005555568a76a7 in doSleep(unsigned int) (timeToSleepMS=1000) at services/autoproxy/p3i2pbob.cc:64
#4  0x00005555568a88b2 in p3I2pBob::data_tick() (this=0x555558198130) at services/autoproxy/p3i2pbob.cc:299
#5  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555558198130) at util/rsthreads.cc:250
#6  0x000055555692cb71 in RsThread::go() (this=0x555558198130) at util/rsthreads.cc:67
#7  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555558198130) at util/rsthreads.cc:87
#8  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fffdeb26700 (LWP 22614)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c43c16 in UdpLayer::recv_loop() (this=0x55555839b130) at udp/udplayer.cc:282
#2  0x0000555556c43a22 in UdpLayer::run() (this=0x55555839b130) at udp/udplayer.cc:237
#3  0x0000555556c75b43 in bdthread_init(void*) (p=0x55555839b130) at util/bdthreads.cc:52
#4  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7fffdf327700 (LWP 22613)):
#0  0x00007ffff548d47f in select () at /usr/lib/libc.so.6
#1  0x0000555556c43c16 in UdpLayer::recv_loop() (this=0x5555582d4e30) at udp/udplayer.cc:282
#2  0x0000555556c43a22 in UdpLayer::run() (this=0x5555582d4e30) at udp/udplayer.cc:237
#3  0x0000555556c75b43 in bdthread_init(void*) (p=0x5555582d4e30) at util/bdthreads.cc:52
#4  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffdfc9f700 (LWP 22605)):
#0  0x00007ffff589bafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffe42941ac in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fffe4293ee8 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe553c700 (LWP 22604)):
#0  0x00007ffff548ac21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff463fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff463ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5c06fc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff5bb28cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff59fbeb9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007fffeea3cba6 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007ffff5a05f65 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffed309700 (LWP 22603)):
#0  0x00007ffff548ac21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff520d630 in  () at /usr/lib/libxcb.so.1
#2  0x00007ffff520f2db in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fffeeb41c5a in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff5a05f65 in  () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffef795700 (LWP 22602)):
#0  0x00007ffff54626a8 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff548dd08 in usleep () at /usr/lib/libc.so.6
#2  0x000055555692df9f in rstime::rs_usleep(unsigned int) (micro_seconds=100000) at util/rstime.cc:42
#3  0x0000555556b33596 in AuthGPG::data_tick() (this=0x555557bf9d50) at pqi/authgpg.cc:193
#4  0x000055555692d1d5 in RsTickingThread::runloop() (this=0x555557bf9df8) at util/rsthreads.cc:250
#5  0x000055555692cb71 in RsThread::go() (this=0x555557bf9df8) at util/rsthreads.cc:67
#6  0x000055555692cbd9 in RsThread::rsthread_init(void*) (p=0x555557bf9df8) at util/rsthreads.cc:87
#7  0x00007ffff5895a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff5495b23 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fffef799200 (LWP 22598)):
#0  0x00007ffff548ac21 in poll () at /usr/lib/libc.so.6
#1  0x00007ffff463fee0 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff463ffce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5c06fc9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007fffeebd7e12 in  () at /usr/lib/libQt5XcbQpa.so.5
#5  0x00007ffff5bb28cc in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff5bbabc6 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#7  0x000055555610078c in main(int, char**) (argc=1, argv=0x7fffffffdfc8) at main.cpp:553
(gdb) 
`

**Comment by defnax** [comment]
@csoler close
