### ISSUE TITLE
Crash on Linux (since two days)

### ISSUE THREAD

**Issue by heini** [RetroShare/RetroShare#264]
This is on Debian Stretch, where RS started to crash reproducably two days ago. The interesting thing here is that the very same version was running fine since last weekend. Here are the last couple of lines from stdout:

```
Cleaning known IPs for all peers.
pqipersongrp::removePeer() id: 0cedfc240413955155b5761bcf16508a
pqipersongrp::removePeer() id: a79060a04989822f357ac9c18708da95
pqipersongrp::removePeer() id: c27c18504e7065d395fce92a91eec3b5
pqipersongrp::removePeer() id: ce5ba7ac2f86a154dbb4473c4fb695c9
Error executing statement (code: 11)
bdNode::checkPotentialPeer(f3c400b483072ac753a02b32df6504d5a87b4d4d ip:185.52.140.241:33464) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
(EE) Key for GXS Id a93cf2fe975f7d06ca25dc02d54aef5f is not available. Cannot verify.
    verifying item signature: FAILED! Droping that item    You probably received a message from a person you don't have key.
    Signature key ID: a93cf2fe975f7d06ca25dc02d54aef5f
bdNode::checkPotentialPeer(f0006e29d6d10b10c3152efdc17aa3db119cd93c ip:185.52.140.250:11531) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
Error executing statement (code: 11)
bdNode::checkPotentialPeer(18a42a49fc0328f53a8f70c62201518e6159bc66 ip:185.52.140.202:50323) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 8 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 9 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 9 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 10 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 10 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 10 peers).
Error executing statement (code: 11)
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 11 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 11 peers).
p3turtle: ERROR: received a tunnel response twice. That should not happen.
Error executing statement (code: 11)
Error executing statement (code: 11)
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Error executing statement (code: 11)
RsSerialiser::deserialise() ERROR deserialiser missing!RsSerialiser::deserialise() PacketId: 0
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Error executing statement (code: 11)
p3discovery2::statusChange() Disconnected: 4d287230525916a03c4ea487c43bc7bc
bdNode::checkPotentialPeer(f69ace89e7cd5785ccd937685c4dfb1029c0ef31 ip:185.52.140.222:39490) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 11 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 11 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 12 peers).
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 12 peers).
bdNode::checkPotentialPeer(19ba7c53ceaf2c5f3d183c70aa8bbdf76ae793b5 ip:185.52.140.208:19075) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Error executing statement (code: 11)
bdNode::checkPotentialPeer(9ecbea39ff25ca5477ca8112a0492802726e5dd2 ip:185.52.140.245:12914) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
Error executing statement (code: 11)
Error executing statement (code: 11)
p3turtle: ERROR: received a tunnel response twice. That should not happen.
Error executing statement (code: 11)
Error executing statement (code: 11)
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
p3PeerMgr::  Current external address is calculated to be: 217.83.210.210 (simultaneously reported by 12 peers).
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
Error executing statement (code: 11)
bdNode::checkPotentialPeer(dbf0960d740d3690a0a84448a9f0783f14483273 ip:185.52.140.250:28956) BAD ADDRESS!!!! SHOULD DISCARD POTENTIAL PEER
Error executing statement (code: 11)
(EE) SSGxsChannelGroup::load() asked to load a null string. Weird.
(EE) SSGxsChannelGroup::load() asked to load a null string. Weird.
(EE) SSGxsChannelGroup::load() asked to load a null string. Weird.
(EE) SSGxsChannelGroup::load() asked to load a null string. Weird.
p3ServiceServer::sendItem() Fails Filtering for packet id=2021904, and peer 83a3b35fe19b63dcaed0a56ddbbda6f3
p3ServiceServer::sendItem() Fails Filtering for packet id=2021904, and peer c70ea77efafe2c3abb4345795b16a210
sockaddr_storage_port() invalid addr.ss_family
sockaddr_storage_dump(addr) unknown addr.ss_family 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
stack trace:
  RetroShare06 : p3Peers::getPeerDetails(t_RsGenericIdType<16u, false, 1u> const&, RsPeerDetails&)+0x65a
  RetroShare06 : p3GxsReputation::updateActiveFriends()+0xe3
  RetroShare06 : p3GxsReputation::tick()+0x6d
  RetroShare06 : p3ServiceServer::tick()+0x62
  RetroShare06 : pqipersongrp::tick()+0x4f
  RetroShare06 : RsServer::data_tick()+0xac
  RetroShare06 : RsTickingThread::runloop()+0x21
  RetroShare06 : RsThread::rsthread_init(void*)+0x1f
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x7284
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x6d
void p3GxsReputation::cleanup(): not implemented. TODO!
Deleting identity 15c3db18561859b8937b1ac64eb79063 which is too old.
Deleting identity 2ddfa437679f63a9ce9b33a73a72a4f5 which is too old.
Cleaning known IPs for all peers.
Error executing statement (code: 11)
Error executing statement (code: 11)
Error executing statement (code: 11)
p3ServiceServer::sendItem() Fails Filtering for packet id=2021140, and peer 83a3b35fe19b63dcaed0a56ddbbda6f3
Group Id list is empty
GxsTokenQueue::checkRequests() ERROR Request Failed: 0
[1]    4860 segmentation fault  RetroShare06
```

Version info:

```
RetroShare Version: 0.6.0x Revision 955df889
Debian GNU/Linux stretch/sid QT 5.5.1

libretroshare
 - bzip2: 1.0.6, 6-Sept-2010
 - OpenSSL: OpenSSL 1.0.2e 3 Dec 2015
 - SQLCipher: 3.8.6
 - Zlib: 1.2.8

RetroShare
 - Libmicrohttpd: 0.9.44

FeedReader
 - LibCurl: 7.46.0
 - Libxml2: 2.9.3
 - libxslt: 1.1.28

VOIP
 - OpenCV: 2.4.9.1
 - Speex: 1.2rc1
```

Anything else I can provide to help fix the problem?

**Comment by csoler** [comment]
Could you by chance provide a callstack? To do that:
- lauch RS with gdb
- when crashes, type "where", and send us the output

Thx!

**Comment by heini** [comment]
Here you are:

```
(gdb) where
#0  0x00007ffff44ae7bd in write () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff65d1bd5 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
#2  0x00007ffff65cfbfc in BIO_write () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
#3  0x00007ffff6f82492 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
#4  0x00007ffff6f82b85 in ?? () from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
#5  0x0000000000c71584 in pqissl::senddata(void*, int) ()
#6  0x0000000000bf2698 in pqistreamer::handleoutgoing_locked() ()
#7  0x0000000000bf227c in pqistreamer::tick_send(unsigned int) ()
#8  0x0000000000bf445c in pqithreadstreamer::data_tick() ()
#9  0x0000000000abd391 in RsTickingThread::runloop() ()
#10 0x0000000000abd13f in RsThread::rsthread_init(void*) ()
#11 0x00007ffff44a6284 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007ffff394d97d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by heini** [comment]
Looks like the crashes were caused by updates of some other packages I did this week, which would explain why it worked fine until thursday. I've recompiled latest revision today and crashes are gone again.
