### ISSUE TITLE
retroshare crashes reliably after about a minute

### ISSUE THREAD

**Issue by hasufell** [RetroShare/RetroShare#394]
without me actually doing anything

gdb backtrace is not particularly useful:

```
Thread 38 "RetroShare06" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb2ffd700 (LWP 10740)]
0x00007ffff31ae278 in raise () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
(gdb) bt
#0  0x00007ffff31ae278 in raise () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007ffff31af6ca in abort () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00007ffff394a4f8 in _Unwind_SetGR (context=<optimized out>, index=<optimized out>, val=<optimized out>)
    at /var/tmp/paludis/build/sys-devel-gcc-5.3.0-r5/work/gcc-5.3.0/libgcc/unwind-dw2.c:271
#3  0x00007ffff38a4b02 in __gxx_personality_v0 ()
    at /usr/x86_64-pc-linux-gnu/lib/libstdc++.so.6
#4  0x00007fffcb7e6d29 in _Unwind_ForcedUnwind_Phase2 (exc=exc@entry=0x7fffb2ffdd70, context=context@entry=0x7fffb2ffcc60)
    at /var/tmp/paludis/build/sys-libs-libgcc-5.3.0/work/gcc-5.3.0/libgcc/unwind.inc:175
#5  0x00007fffcb7e7080 in _Unwind_ForcedUnwind (exc=0x7fffb2ffdd70, stop=0x7ffff3ba9a10 <unwind_stop>, stop_argument=0x7fffb2ffcef0)
    at /var/tmp/paludis/build/sys-libs-libgcc-5.3.0/work/gcc-5.3.0/libgcc/unwind.inc:207
#6  0x00007ffff3ba9b90 in __pthread_unwind ()
    at /usr/x86_64-pc-linux-gnu/lib/libpthread.so.0
#7  0x00007ffff3ba24e5 in  () at /usr/x86_64-pc-linux-gnu/lib/libpthread.so.0
#8  0x0000000000c470bb in  ()
#9  0x00007ffff3ba13d4 in start_thread ()
    at /usr/x86_64-pc-linux-gnu/lib/libpthread.so.0
#10 0x00007ffff3262d6d in clone () at /usr/x86_64-pc-linux-gnu/lib/libc.so.6
```

retoshare version it 0.6.0

**Comment by G10h4ck** [comment]
This is probably fixed already. We are at 0.6.5
